services:
  app:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${IMAGE_REPOSITORY}:${IMAGE_TAG}
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile.deploy
    tty: true
