services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
      args:
        CONTAINER_USER: ${CONTAINER_USER:-appuser}
        CONTAINER_GID: ${CONTAINER_GID:-1000}
        CONTAINER_UID: ${CONTAINER_UID:-1000}
    tty: true
    volumes:
      - ./src:/app
      - ./data/app/.cache:/home/${CONTAINER_USER}/.cache
    ports:
      - 18000:8000
    environment:
      FASTAPI_PORT: 8000
      FASTAPI_HOST: 0.0.0.0
      FASTAPI_RELOAD: True
      API_KEY: ${API_KEY-}
      DOMAIN_NAME: yamashiro.work
      AWS_REGION: ${AWS_REGION:-ap-northeast-1}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-test}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-test}
    command: ["/usr/local/bin/startup.sh"]
  terraform:
    container_name: terraform
    image: hashicorp/terraform:1.11.4
    volumes: 
      - ./terraform:/work
    working_dir: /work
    environment:
      AWS_DEFAULT_REGION: ${AWS_REGION:-ap-northeast-1}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-test}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-test}
      LAMBDA_FUNCTION_NAME: ${LAMBDA_FUNCTION_NAME:-microDDNS}
      DOMAIN_NAME: ${DOMAIN_NAME:-micro-ddns.net}
      API_KEY: ${API_KEY-}


